---
- name: Add runner directory
  shell: mkdir -p actions-runner
- name: Download runner
  shell: curl -o actions-runner/actions-runner-linux-x64-2.286.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.286.1/actions-runner-linux-x64-2.286.1.tar.gz
- name: extract runner
  shell: cd actions-runner && tar xzf ./actions-runner-linux-x64-2.286.1.tar.gz
- name: set correct perms
  file: dest=./actions-runner owner=ec2-user group=ec2-user mode=u=rwX,g=rX,o=rX recurse=yes
