apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
