name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app:$(date +%s)
    - name: Restart app container
      run: docker stop app && docker rm app && docker run -p 8080:8080 --name app app:$(date +%s)
