name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./application/. --file ./application/Dockerfile --tag app:$(date +%s) --tag app:latest
    - name: Restart app container
      run: docker stop app || true && docker rm app || true && docker run -d -p 8080:8080 --name app app:latest
